/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from "kysely";

export type Generated<T> = T extends ColumnType<infer S, infer I, infer U>
  ? ColumnType<S, I | undefined, U>
  : ColumnType<T, T | undefined, T>;

export type Timestamp = ColumnType<Date, Date | string, Date | string>;

export interface Followers {
  created_at: Generated<Timestamp>;
  followed_id: number;
  follower_id: number;
  id: Generated<number>;
}

export interface Likes {
  created_at: Generated<Timestamp>;
  id: Generated<number>;
  post_id: number;
  user_id: number;
}

export interface Posts {
  author_id: number;
  content: string;
  created_at: Generated<Timestamp>;
  id: Generated<number>;
  title: string;
}

export interface Users {
  created_at: Generated<Timestamp>;
  email: string;
  first_name: string;
  id: Generated<number>;
  last_name: string | null;
  password: string;
  username: string;
}

export interface DB {
  followers: Followers;
  likes: Likes;
  posts: Posts;
  users: Users;
}
